version: '3.4'

services:
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  influxdb:
    image: influxdb:1.4.2
    ports:
      - 8086:8086
  chronograf:
    # NOTE: internally binds to 8888
    image: chronograf:1.3.10
    command: --influxdb-url=http://influxdb:8086
    ports:
      - 8888:8888
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELASTIC_VERSION:-6.1.3}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - 9600:9600
      - 4560:4560
      - 12201:12201
      - 12201:12201/udp
  telegraf:
    image: telegraf:1.5.0
    configs:
      - source: telegraf
        target: /etc/telegraf/telegraf.conf
        mode: 0660
    ports:
      - 8125:8125/udp
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.1.3}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION:-6.1.3}
    ports:
      - 5601:5601

volumes:
  mongodb_data:
  es_data:

configs:
  telegraf:
    file: ./telegraf.conf