version: "3.1"

services:
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

  backup:
    image: itzg/mongo-backups:1.0
    volumes:
      - backup_mongodb:/backups
    env_file:
      - rclone.env
    environment:
      HOST: mongodb
      INTERVAL: 43200
      RCLONE_REMOTE_PATH:
    secrets:
      - rclone.conf
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

  kidsbank:
    image: itzg/kidsbank-js:0.3.0
    env_file:
      - social.env
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb

  haproxy:
    image: itzg/haproxy-lets
    env_file:
      - letencrypt.env
    volumes:
      - haproxy_certs:/certs
      - haproxy_config:/config
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

volumes:
  mongodb_data:
  backup_mongodb:
  haproxy_certs:
  haproxy_config:

secrets:
  rclone.conf:
    external: true