spring:
  social:
    facebook:
      app-id: 1260180640753397
  data:
    mongodb:
      database: kidsbank
  mvc:
    media-types:
      xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet