spring:
  data:
    mongodb:
      database: kidsbank
      host: ${mongodbHost:localhost}
  mvc:
    contentnegotiation:
      media-types:
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
logging:
  gelf:
    protocol: TCP
    service: kidsbank
  level:
    org.springframework.web.servlet.DispatcherServlet: info
    me.itzg.kidsbank: ${kidsbank.log-level:info}
management:
  metrics:
    export:
      influx:
        enabled: false
      statsd:
        enabled: false
      stackdriver:
        enabled: false