spring:
  data:
    mongodb:
      database: kidsbank
      host: ${mongodbHost:localhost}
  mvc:
    media-types:
      xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  metrics:
    export:
      influx:
        enabled: false
logging.gelf.service: kidsbank
---
spring:
  profiles: MetricsToInflux
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: kidsbank
        step: PT10S
        enabled: true
logging:
  level:
    io.micrometer.influx.InfluxMeterRegistry: warn
---
spring:
  profiles: MetricsToStatsD
  metrics:
    export:
      statsd:
        enabled: true
        host: localhost
        flavor: telegraf