spring:
  data:
    mongodb:
      database: kidsbank
      host: ${mongodbHost:localhost}
  mvc:
    contentnegotiation:
      media-types:
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
logging:
  gelf:
    protocol: TCP
    service: kidsbank
management:
  metrics:
    export:
      influx:
        enabled: false
      statsd:
        enabled: false