spring:
  security:
    oauth2:
      client:
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id
        registration:
          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook-client-secret}
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
          linkedin:
            client-id: ${linked-client-id}
            client-secret: ${linked-client-secret}
            scope: r_liteprofile
            client-name: LinkedIn
            authorization-grant-type: authorization_code
            # post => include client_id in body of token request
            client-authentication-method: post
            redirect-uri-template: "{baseUrl}/{action}/oauth2/code/{registrationId}"