version: "3.4"

services:
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

  backup:
    image: itzg/mongo-backups:1.0
    volumes:
      - backup_mongodb:/backups
    env_file:
      - rclone.env
    environment:
      HOST: mongodb
      INTERVAL: 43200
      RCLONE_CONFIG: /var/run/secrets/rclone.conf
    secrets:
      - rclone.conf
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

  kidsbank:
    image: itzg/kidsbank-js:0.3.4
    env_file:
      - social.env
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_PROFILES_ACTIVE: MetricsToTelegraf,gelf
      LOGGING_GELF_SERVER: logstash
      LOGGING_LEVEL_ME_ITZG_KIDSBANK: debug
      SPRING_METRICS_EXPORT_STATSD_HOST: telegraf

  haproxy:
    image: itzg/haproxy-lets
    env_file:
      - letencrypt.env
    volumes:
      - haproxy_certs:/certs
      - haproxy_config:/config
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.volumes == main

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.1
    configs:
      - source: logstash2
        target: /usr/share/logstash/pipeline/logstash.conf
    secrets:
      - ca.pem
      - logstash-client.pem
      - logstash-client-key.pem
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOG_LEVEL: debug
    ports:
      - 5550:5550
    deploy:
      resources:
        limits:
          memory: 512m

  telegraf:
    image: telegraf:1.5.0
    secrets:
      - ca.pem
      - logstash-client.pem
      - logstash-client-key.pem
    configs:
      - source: telegraf
        target: /etc/telegraf/telegraf.conf
        mode: 0660
    ports:
      - 127.0.0.1:8125:8125/udp
    deploy:
      mode: global

volumes:
  mongodb_data:
  backup_mongodb:
  haproxy_certs:
  haproxy_config:

secrets:
  rclone.conf:
    external: true
  ca.pem:
    external: true
  logstash-client.pem:
    external: true
  logstash-client-key.pem:
    external: true

configs:
  logstash2:
    file: ./logstash2.conf
  telegraf:
    file: ./telegraf.conf