---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kidsbank-mongo
    stack: kidsbank
  name: kidsbank-mongo
spec:
  replicas: 1
  serviceName: kidsbank-mongo
  selector:
    matchLabels:
      app: kidsbank-mongo
  template:
    metadata:
      labels:
        app: kidsbank-mongo
    spec:
      containers:
        - image: mongo:3.6.16
          name: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: kidsbank-mongo-data
  volumeClaimTemplates:
    - metadata:
        name: kidsbank-mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kidsbank-mongo
  labels:
    stack: kidsbank
spec:
  selector:
    app: kidsbank-mongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None