version: '3.4'

services:
  kidsbank:
    image: itzg/kidsbank-js:0.5-SNAPSHOT
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_PROFILES_ACTIVE: LogToLogstash
      SPRING_METRICS_EXPORT_INFLUX_URI: http://influxdb:8086
      LOGSTASH_DEST: logstash:4560
    ports:
      - 8080:8080
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: