version: '3.4'

services:
  kidsbank:
    image: itzg/kidsbank-js:0.4-SNAPSHOT
    env_file:
      - ../prod/social.env
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_PROFILES_ACTIVE: MetricsToInflux,gelf
      SPRING_METRICS_EXPORT_INFLUX_URI: http://influxdb:8086
      LOGGING_GELF_SERVER: logstash
    ports:
      - 8080:8080
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db
  influxdb:
    image: influxdb:1.4.2
  chronograf:
    image: chronograf:1.3.10
    command: --influxdb-url=http://influxdb:8086
    ports:
      - 8888:8888
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - 9600:9600
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    ports:
      - 5601:5601

volumes:
  mongodb_data:
  es_data:

configs:
  logstash:
    file: ./logstash.conf